"""
live/strategy.py — FCB (First Candle Breakout) strategy logic.

Pure functions — no exchange calls.  Takes candle data in, returns signals out.

Workflow per session per pair:
  1. Capture first 5m candle high/low after session open.
  2. Validate range >= 0.3%.
  3. On candle #2 close: check if close > high (long) or close < low (short).
  4. If breakout: compute entry, SL (midpoint), TP (1.5R), position size.
  5. Return a TradeSignal.
"""

from dataclasses import dataclass
from typing import Optional, Dict, List
from live.config import TP_R, MIN_RANGE_PCT, FEE_RATE, RISK_PCT, SCALE_RISK_PCT


@dataclass
class FirstCandle:
    """Captured first-candle data for a pair in a session."""
    symbol: str
    session: str
    high: float
    low: float
    midpoint: float
    range_pct: float       # (high - low) / midpoint
    valid: bool            # range >= MIN_RANGE_PCT
    open: float = 0.0
    close: float = 0.0
    volume: float = 0.0


@dataclass
class TradeSignal:
    """A trade signal generated by the FCB strategy."""
    symbol: str
    session: str
    direction: str         # "long" or "short"
    entry_price: float     # close of candle 2
    stop_loss: float       # midpoint of candle 1
    take_profit: float     # entry ± 1.5R
    risk_per_unit: float   # abs(entry - sl)
    fee_r: float           # 2 * fee_rate * entry / risk_per_unit
    position_size: float   # quantity to trade (in base units)


@dataclass
class ScaleSignal:
    """A limit-order scale-in signal at FC boundary."""
    symbol: str
    session: str
    direction: str         # same direction as base trade
    limit_price: float     # FC high (long) or FC low (short)
    stop_loss: float       # same midpoint as base
    take_profit: float     # limit_price ± 1.5R (calculated from limit entry)
    risk_per_unit: float   # abs(limit_price - sl)
    fee_r: float           # 2 * fee_rate * limit_price / risk_per_unit
    position_size: float   # quantity for scale-in


def capture_first_candle(symbol: str, session: str, candle: Dict) -> FirstCandle:
    """
    Capture first candle stats.

    candle: dict with keys {high, low, open, close}
    """
    h = candle["high"]
    l = candle["low"]
    mid = (h + l) / 2.0

    if mid <= 0:
        return FirstCandle(symbol, session, h, l, mid, 0.0, False)

    range_pct = (h - l) / mid

    return FirstCandle(
        symbol=symbol,
        session=session,
        high=h,
        low=l,
        midpoint=mid,
        range_pct=range_pct,
        valid=range_pct >= MIN_RANGE_PCT,
        open=candle.get("open", 0.0),
        close=candle.get("close", 0.0),
        volume=candle.get("volume", 0.0),
    )


def check_breakout(fc: FirstCandle, candle2_close: float) -> Optional[str]:
    """
    Check if candle 2's close breaks out of candle 1's range.
    Returns "long", "short", or None.
    """
    if not fc.valid:
        return None

    if candle2_close > fc.high:
        return "long"
    elif candle2_close < fc.low:
        return "short"
    return None


def compute_signal(
    fc: FirstCandle,
    direction: str,
    entry_price: float,
    equity: float,
    contract_size: float = 1.0,
    price_precision: int = 4,
    qty_precision: int = 2,
    min_qty: float = 0.001,
    min_notional: float = 5.0,
    risk_pct: float = None,
) -> Optional[TradeSignal]:
    """
    Compute full trade signal with position sizing.

    equity: current USDT account equity
    contract_size: exchange contract multiplier (usually 1 for linear)
    risk_pct: fraction of equity to risk (defaults to RISK_PCT from config)
    """
    if risk_pct is None:
        risk_pct = RISK_PCT
    sl = fc.midpoint
    risk_per_unit = abs(entry_price - sl)

    if risk_per_unit <= 0:
        return None

    # Take profit
    if direction == "long":
        tp = entry_price + TP_R * risk_per_unit
    else:
        tp = entry_price - TP_R * risk_per_unit

    # Fee in R
    fee_r = 2.0 * FEE_RATE * entry_price / risk_per_unit

    # Position sizing: risk risk_pct of equity
    risk_amount = equity * risk_pct                    # USDT amount at risk
    qty_base = risk_amount / risk_per_unit             # base units
    qty_contracts = qty_base / contract_size           # in contract units

    # Check minimum notional
    notional = qty_contracts * contract_size * entry_price
    if min_notional and notional < min_notional:
        return None

    # Check minimum quantity
    if min_qty and qty_contracts < min_qty:
        return None

    return TradeSignal(
        symbol=fc.symbol,
        session=fc.session,
        direction=direction,
        entry_price=entry_price,
        stop_loss=sl,
        take_profit=tp,
        risk_per_unit=risk_per_unit,
        fee_r=fee_r,
        position_size=qty_contracts,
    )


def compute_scale_signal(
    fc: FirstCandle,
    direction: str,
    equity: float,
    contract_size: float = 1.0,
    price_precision: int = 4,
    qty_precision: int = 2,
    min_qty: float = 0.001,
    min_notional: float = 5.0,
    risk_pct: float = None,
) -> Optional[ScaleSignal]:
    """
    Compute limit-order scale-in signal at FC boundary.

    For longs:  limit buy at FC high (price retraces back to breakout level)
    For shorts: limit sell at FC low
    SL = midpoint (same as base), TP = limit_price +/- 1.5 * scale_risk
    risk_pct: fraction of equity to risk for scale (defaults to SCALE_RISK_PCT)
    """
    if risk_pct is None:
        risk_pct = SCALE_RISK_PCT
    limit_price = fc.high if direction == "long" else fc.low
    sl = fc.midpoint
    risk_per_unit = abs(limit_price - sl)

    if risk_per_unit <= 0:
        return None

    # Take profit based on scale-in entry
    if direction == "long":
        tp = limit_price + TP_R * risk_per_unit
    else:
        tp = limit_price - TP_R * risk_per_unit

    # Fee in R
    fee_r = 2.0 * FEE_RATE * limit_price / risk_per_unit

    # Position sizing: risk risk_pct of equity
    risk_amount = equity * risk_pct
    qty_base = risk_amount / risk_per_unit
    qty_contracts = qty_base / contract_size

    # Check minimums
    notional = qty_contracts * contract_size * limit_price
    if min_notional and notional < min_notional:
        return None
    if min_qty and qty_contracts < min_qty:
        return None

    return ScaleSignal(
        symbol=fc.symbol,
        session=fc.session,
        direction=direction,
        limit_price=limit_price,
        stop_loss=sl,
        take_profit=tp,
        risk_per_unit=risk_per_unit,
        fee_r=fee_r,
        position_size=qty_contracts,
    )
